input:
  examples:
  #  - examples.txt
    - expressions-1.json
  keywords:
  - keywords.yml
  providers:

entities:
  #intent:
  #  model: botshot_nlu.intent.neural_net_model.NeuralNetModel
  #  tokenizer: botshot_nlu.tokenizer.whitespace.WhitespaceTokenizer
  #  featurizer: botshot_nlu.pipeline.featurizer.BagOfWordsFeaturizer
  course:
    keywords:
      model: botshot_nlu.keywords.trie.TrieKeywordExtractor
  fruit:
    keywords:
      model: botshot_nlu.keywords.embedding.EmbeddingKeywordExtractor
      embedding_file: /home/goovi/datasets/fasttext-en/cc.en.300.vec
  color:
    keywords:
      model: botshot_nlu.keywords.embedding.EmbeddingKeywordExtractor
      embedding_file: /home/goovi/datasets/fasttext-en/cc.en.300.vec
